pose_model: ""
fall_model:
    in_channels: 2
    num_classes: 1
    graph_args:
        layout: 'coco'
        strategy: 'spatial'
        max_hop: 1
    edge_importance_weighting: true
    dropout: 0.5
    use_contrastive_block: true

loss:
    use_contrastive_loss: false
    use_focal_loss: true
    use_transition_loss: false
    weight_loss: [1, 1, 1, 1, 1] # ts, cls, trans, ct, ct_cls

data:
    root: 'datasets/le2i'
    augmentations:
        add_noise: true
        flip_lr: true
        scale: true
        translate: true

    use_kalman: true
    train_batch_size: 64
    val_batch_size: 64

    mixup_data: 
        data_name: ''
        mixup_percentage: 0.0

    preprocess:
        detect_model: 
            ckpt: 'weights/yolo11x-pose.pt'
            img_size: 640
            conf: 0.8
        kalman:
            limited_distance:
                dist: 20
                use: false
            num_missing: 3
        dataset: 'urfall' # [urfall, le2i]
        data_root: 'datasets/urfall'
        visualize: false


train:
    num_epochs: 1000
    optimizer: 'Adam'
    lr: 0.001


val:
    threshold:
        timestamp: 0.5 # make_sequence line 67: normalized_gaussian
        classify: 0.5  # make_sequence line 139: filter_timestamp
    # ckpt: 'checkpoints/le2i_v7_noct/weights/model_epoch_458_recall.pth'
    ckpt: 'checkpoints/urfall_v11/weights/model_epoch_31_recall.pth'
    



experiment_name: 'le2i_v7_noct'
workspace_dir: 'checkpoints'
device: 'cuda:0'
seed: 5432